### ISSUE TITLE
Full docker-compose.yml with external Hazelcast is not working

### ISSUE THREAD

**Issue by younes-io** [camunda-community-hub/zeebe-hazelcast-exporter#175]
Hello,

I ran the docker-compose.yml in the README file, and I changed the `hazelcast-management` version to `4.2022.01`, and I get this error : 

![image](https://user-images.githubusercontent.com/3153107/159079339-81cb77dd-206a-4b7d-8aee-941a43ecf8cd.png)

This is my docker configuration:

```yaml
version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:1.1.2
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_HAZELCAST_REMOTE_ADDRESS=hazelcast:5701
    ports:
      - "26500:26500"
      - "9600:9600"
    volumes:
      - ../exporter/target/zeebe-hazelcast-exporter-1.0.1-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
    depends_on:
      - hazelcast

  hazelcast:
    container_name: hazelcast
    image: hazelcast/hazelcast:4.2
    ports:
      - "5701:5701"
    environment:
      - JAVA_OPTS="-Dhazelcast.local.publicAddress=hazelcast:5701"
    networks:
      - zeebe_network
      
  hazelcast-management:
    container_name: hazelcast-management
    image: hazelcast/management-center:4.2022.01
    ports:
      - "8083:8080"
    networks:
      - zeebe_network
    depends_on:
      - hazelcast    
```

Do you have the same issue?
